name: Publish packages to npm
on:
  push:
    branches:
      - master
jobs:
  publish-on-push:
    runs-on: self-hosted
    name: publish-on-push
    steps:
      - uses: actions/checkout@v3
      - name: Use .npmrc
        uses: bduff9/use-npmrc@v1.1
        with:
          dot-npmrc: |
            unsafe-perm=true
            //registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: build @ag-media/eslint-config-nextjs
        working-directory: eslint-nextjs
        run: npm run build

      - name: publish @ag-media/eslint-config
        working-directory: eslint
        run: npm publish --access public
      - name: publish @ag-media/eslint-config-nextjs
        working-directory: eslint-nextjs
        run: npm publish --access public
      - name: publish @ag-media/stylelint-config
        working-directory: stylelint
        run: npm publish --access public
