name: Publish packages to npm
on:
  push:
    branches:
      - master
jobs:
  publish-eslint-config:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: eslint
    steps:
      - uses: actions/checkout@v3
      - name: Use .npmrc
        uses: bduff9/use-npmrc@v1.1
        with:
          dot-npmrc: |
            unsafe-perm=true
            //registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Check version
        id: package_version
        run: |
          export PACKAGE_VERSION="$(node -p -e "require('./package.json').version")"
          export PACKAGE_NAME="$(node -p -e "require('./package.json').name")"

          IS_NEW_VERSION=$(npm view "$PACKAGE_NAME@$PACKAGE_VERSION" versions 1>/dev/null 2>/dev/null && echo true || echo false)
          echo "is_new=$IS_NEW_VERSION\n" >> $GITHUB_OUTPUT
      - name: debug
        run: echo $is_new
        env:
          is_new: ${{steps.package_version.outputs.is_new}}
      - name: Install
        run: npm ci --no-optional
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish --access public
        if: steps.package_version.outputs.is_new == 'true'
